#!/bin/bash
set -Eeu -o pipefail

if command -v docker &>/dev/null; then
  docker container run \
    --name "rubocop_$(uuidgen | head -c8)" \
    --rm \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work:ro \
    ghcr.io/shakiyam/rubocop "$@"
elif command -v podman &>/dev/null; then
  podman container run \
    --name "rubocop_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -t \
    -v "$PWD":/work:ro \
    ghcr.io/shakiyam/rubocop "$@"
else
  echo 'Neither docker nor podman is installed.' >&2
  exit 1
fi
